import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'
import NavBar from './NavBar/Navbar.jsx'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <NavBar></NavBar>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti excepturi id dolores blanditiis repellat unde voluptates vitae omnis magni dicta similique nulla explicabo nam cum consequuntur quod praesentium, eveniet odit, et vero, maxime nemo? Neque qui dolorem sunt nisi fuga optio ullam placeat, id magnam vero numquam? Iusto sunt corrupti dolor, laboriosam exercitationem quas, possimus aut numquam error, assumenda nisi quis! Ducimus ad a laborum qui! Itaque facere accusantium rem vitae culpa voluptates quo architecto eos magni voluptatum odit quis, fugiat repellendus, hic nisi unde, fugit necessitatibus atque. Voluptatum molestiae aspernatur eos optio adipisci ullam enim. Aperiam assumenda similique dolore exercitationem iste quod accusantium unde fugit reprehenderit, itaque quasi rerum perspiciatis veritatis ipsam veniam a nisi tenetur alias! Consectetur facilis aspernatur nam! Doloribus nobis, aperiam tempora qui illum veniam deleniti fuga amet rerum, corporis sequi soluta laudantium eligendi, dolores consequatur itaque sint ullam temporibus sed! Nemo dolore, doloribus dolorem facere beatae at ducimus perspiciatis minima velit ut corporis laboriosam, illum corrupti distinctio fugit molestiae culpa quibusdam enim porro possimus? Quo, error illum suscipit reprehenderit, autem alias asperiores enim vel nam a placeat iure sequi est ipsum repellat officia assumenda similique sit temporibus nobis fugit voluptatem minima ea. Dolor corporis alias porro reiciendis modi minima, deleniti ea! Excepturi non iusto repellat quis adipisci magnam eaque similique cumque at eum? Unde repudiandae eum provident cupiditate accusantium dolore mollitia modi, non est, quasi repellendus alias libero laboriosam earum ipsum pariatur facere, ab architecto minus vitae. Placeat nobis cum consequuntur, recusandae deserunt a amet voluptate, ex officiis alias ea maxime, ipsam distinctio ab velit et quaerat in? Culpa quod harum magni. Beatae eum non quos, tempora cumque numquam quod enim aliquam officia reprehenderit in nulla quam magni minus ad, officiis, at deleniti doloribus. Eveniet, aliquid. Tempore non dolore hic ipsum nisi, fugit nam accusamus quaerat ad veritatis obcaecati nihil iusto incidunt! Ipsam repudiandae necessitatibus porro eligendi! Omnis maxime ut rerum est autem. Atque possimus, optio at doloribus numquam ipsam provident quibusdam deserunt maiores suscipit? Officia libero tempora nihil, numquam dolorem obcaecati perspiciatis? Doloribus mollitia ullam dolor rem. Atque, aliquam ab impedit eligendi corrupti cum vitae maiores itaque, voluptatibus in quidem eaque inventore, illo nobis culpa quae cupiditate debitis odio delectus beatae ipsum unde commodi porro. Recusandae beatae ipsam hic at, dignissimos reprehenderit tempora incidunt voluptatum placeat iusto voluptatibus, facilis reiciendis exercitationem excepturi possimus architecto illum accusamus sequi perferendis, ea praesentium facere dolorem! Impedit, voluptates.
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti excepturi id dolores blanditiis repellat unde voluptates vitae omnis magni dicta similique nulla explicabo nam cum consequuntur quod praesentium, eveniet odit, et vero, maxime nemo? Neque qui dolorem sunt nisi fuga optio ullam placeat, id magnam vero numquam? Iusto sunt corrupti dolor, laboriosam exercitationem quas, possimus aut numquam error, assumenda nisi quis! Ducimus ad a laborum qui! Itaque facere accusantium rem vitae culpa voluptates quo architecto eos magni voluptatum odit quis, fugiat repellendus, hic nisi unde, fugit necessitatibus atque. Voluptatum molestiae aspernatur eos optio adipisci ullam enim. Aperiam assumenda similique dolore exercitationem iste quod accusantium unde fugit reprehenderit, itaque quasi rerum perspiciatis veritatis ipsam veniam a nisi tenetur alias! Consectetur facilis aspernatur nam! Doloribus nobis, aperiam tempora qui illum veniam deleniti fuga amet rerum, corporis sequi soluta laudantium eligendi, dolores consequatur itaque sint ullam temporibus sed! Nemo dolore, doloribus dolorem facere beatae at ducimus perspiciatis minima velit ut corporis laboriosam, illum corrupti distinctio fugit molestiae culpa quibusdam enim porro possimus? Quo, error illum suscipit reprehenderit, autem alias asperiores enim vel nam a placeat iure sequi est ipsum repellat officia assumenda similique sit temporibus nobis fugit voluptatem minima ea. Dolor corporis alias porro reiciendis modi minima, deleniti ea! Excepturi non iusto repellat quis adipisci magnam eaque similique cumque at eum? Unde repudiandae eum provident cupiditate accusantium dolore mollitia modi, non est, quasi repellendus alias libero laboriosam earum ipsum pariatur facere, ab architecto minus vitae. Placeat nobis cum consequuntur, recusandae deserunt a amet voluptate, ex officiis alias ea maxime, ipsam distinctio ab velit et quaerat in? Culpa quod harum magni. Beatae eum non quos, tempora cumque numquam quod enim aliquam officia reprehenderit in nulla quam magni minus ad, officiis, at deleniti doloribus. Eveniet, aliquid. Tempore non dolore hic ipsum nisi, fugit nam accusamus quaerat ad veritatis obcaecati nihil iusto incidunt! Ipsam repudiandae necessitatibus porro eligendi! Omnis maxime ut rerum est autem. Atque possimus, optio at doloribus numquam ipsam provident quibusdam deserunt maiores suscipit? Officia libero tempora nihil, numquam dolorem obcaecati perspiciatis? Doloribus mollitia ullam dolor rem. Atque, aliquam ab impedit eligendi corrupti cum vitae maiores itaque, voluptatibus in quidem eaque inventore, illo nobis culpa quae cupiditate debitis odio delectus beatae ipsum unde commodi porro. Recusandae beatae ipsam hic at, dignissimos reprehenderit tempora incidunt voluptatum placeat iusto voluptatibus, facilis reiciendis exercitationem excepturi possimus architecto illum accusamus sequi perferendis, ea praesentium facere dolorem! Impedit, voluptates.
      </p>
    </div>
  )

}



export default App
